default: &default
  host: localhost
  user: postgres
  password: password
  adapter: postgres

development:
  <<: *default
  db: milenio

test:
  <<: *default
  db: application_database_name_test

production:
  <<: *default
  db: application_database_name_production